apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260530-210224-rfx9dg2mzc6p-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260530-210224-rfx9dg2mzc6p.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260530-210224-rfx9dg2mzc6p-service
            port:
              number: 80
